<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fr.paris.lutece.tools</groupId>
    <artifactId>lutece-global-pom</artifactId>
    <version>5.0.2</version>
  </parent>
  <groupId>fr.paris.lutece.plugins</groupId>
  <artifactId>module-leaflet-bienvu</artifactId>
  <version>0.0.6</version>
  <packaging>lutece-plugin</packaging>
  <name>Lutece Leaflet module for bien VU</name>
  <url>https://github.com/plainecommune/espacepublic-module-dansmarue-leaflet</url>
  <scm>
    <connection>scm:git:https://github.com/plainecommune/espacepublic-module-dansmarue-leaflet.git</connection>
    <developerConnection>scm:git:https://github.com/plainecommune/espacepublic-module-dansmarue-leaflet.git</developerConnection>
    <url>https://github.com/plainecommune/espacepublic-module-dansmarue-leaflet</url>
    <tag>module-leaflet-bienvu-0.0.6</tag>
  </scm>
  <properties>
    <sonar.language>java</sonar.language>
    <componentName>leaflet-dansmarue</componentName>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <sonar.sources>src/java</sonar.sources>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>fr.paris.lutece</groupId>
        <artifactId>lutece-core</artifactId>
        <version>6.1.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>fr.paris.lutece</groupId>
      <artifactId>lutece-core</artifactId>
      <version>6.1.0</version>
      <type>lutece-core</type>
    </dependency>
    <dependency>
      <groupId>fr.paris.lutece.plugins</groupId>
      <artifactId>plugin-leaflet</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>fr.paris.lutece.plugins</groupId>
      <artifactId>library-httpaccess</artifactId>
      <version>2.5.1</version>
    </dependency>
  </dependencies>

   <repositories>
        <repository>
            <id>luteceReleaseRepository</id>
            <name>luteceReleaseRepository</name>
            <url>https://dev.lutece.paris.fr/nexus/content/groups/maven_repository/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>luteceSnapshotRepository</id>
            <name>luteceSnapshotRepository</name>
            <url>https://dev.lutece.paris.fr/nexus/content/groups/snapshot_repository/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-release-plugin</artifactId>
        <version>2.5.3</version>
        <configuration combine.self="override">
          <tagNameFormat>module-leaflet-bienvu-@{project.version}</tagNameFormat>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.7.4.201502262128</version>
        <executions>
          <execution>
            <id>pre-unit-test</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
            <configuration>
              <destFile>../target/coverage-reports/jacoco-unit.exec</destFile>
              <append>true</append>
            </configuration>
          </execution>
          <execution>
            <id>post-unit-test</id>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
            <configuration>
              <dataFile>../target/coverage-reports/jacoco-unit.exec</dataFile>
              <outputDirectory>../target/coverage-reports/jacoco-ut</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
